# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   username: postgres
#   password: postgres

# development:
#   <<: *default
#   database: gitos_development

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gitos_development
  pool: 5
  username: root
  password: "root"

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gitos_development
  pool: 5
  username: root
  password: "root"

